sudo: false
language: node_js
node_js:
  - node
services:
  - mongodb
  - redis-server
  - mysql
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test