sudo: false
language: node_js
node_js:
  - node
services:
  - mongodb
  - redis-server
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE yogurt_test CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
  - mysql -e 'CREATE TABLE yogurt_test.staff
             (
               staffId      VARCHAR(45)  NOT NULL,
               companyId    INT UNSIGNED NULL,
               isInit       TINYINT      NULL,
               name         VARCHAR(45)  NULL,
               email        VARCHAR(45)  NULL,
               tel          VARCHAR(45)  NULL,
               nickname     VARCHAR(45)  NULL,
               password     VARCHAR(45)  NULL,
               picUrl       VARCHAR(200) NULL,
               role         VARCHAR(45)  NULL,
               onlineStatus TINYINT      NULL,
               servingCount INT UNSIGNED NULL,
               waitingCount INT UNSIGNED NULL,
               queueCount   INT UNSIGNED NULL,
               id           INT UNSIGNED AUTO_INCREMENT
                 PRIMARY KEY,
               AnsAsk       VARCHAR(200) NULL,
               CONSTRAINT id_UNIQUE
               UNIQUE (staffId)
             )
               ENGINE = InnoDB;'
  - mysql -e 'CREATE TABLE yogurt_test.comments
             (
              id      INT AUTO_INCREMENT
                PRIMARY KEY,
               userId       VARCHAR(45)  NULL,
               staffId      VARCHAR(45)  NULL,
               content      VARCHAR(512) NULL,
               star         INT          NULL,
               date         DATETIME     NULL,
               remark       VARCHAR(256) NULL
             )
                ENGINE = InnoDB;'
  - mysql -e 'CREATE TABLE yogurt_test.company
             (
               id               INT AUTO_INCREMENT
                 PRIMARY KEY,
               name             VARCHAR(45)             NULL,
               picUrl           VARCHAR(200)            NULL,
               robotAvatar      VARCHAR(300)            NULL,
               corpusFile       VARCHAR(200) DEFAULT '' NULL,
               robotWelcome     VARCHAR(200) DEFAULT '' NULL,
               managerId        VARCHAR(200) DEFAULT '' NOT NULL,
               totalServeCount  INT DEFAULT '0'         NOT NULL,
               totalAnsAsk      VARCHAR(200) DEFAULT '' NOT NULL,
               totalNoteCount   INT DEFAULT '0'         NOT NULL,
               repliedNoteCount INT DEFAULT '0'         NOT NULL
             )
               ENGINE = InnoDB;'
  - mysql -e 'CREATE TABLE yogurt_test.manager
             (
               id           INT AUTO_INCREMENT
                 PRIMARY KEY,
               companyId    INT UNSIGNED NULL,
               name         VARCHAR(45)  NULL,
               email        VARCHAR(45)  NULL,
               tel          VARCHAR(45)  NULL,
               nickname     VARCHAR(45)  NULL,
               password     VARCHAR(45)  NULL,
               picUrl       VARCHAR(200) NULL,
               onlineStatus INT UNSIGNED NULL,
               managerId    VARCHAR(45)  NULL,
               CONSTRAINT managerId_UNIQUE
               UNIQUE (managerId)
             )
               ENGINE = InnoDB;'
  - mysql -e 'CREATE TABLE yogurt_test.note
             (
               id        INT AUTO_INCREMENT
                 PRIMARY KEY,
               companyId INT          NULL,
               userId    VARCHAR(45)  NULL,
               content   VARCHAR(257) NULL,
               email     VARCHAR(45)  NULL,
               time      DATETIME     NULL,
               isReplied TINYINT      NULL,
               reply     VARCHAR(257) NULL,
               staffId   VARCHAR(45)  NULL
             )
               ENGINE = InnoDB;'
  - mysql -e 'CREATE TABLE user
              (
                id           INT AUTO_INCREMENT
                  PRIMARY KEY,
                userId       VARCHAR(45)  NOT NULL,
                picUrl       VARCHAR(255) NULL,
                accessTime   DATETIME     NOT NULL,
                accessWay    INT          NOT NULL,
                sourcePage   VARCHAR(255) NOT NULL,
                additionInfo LONGTEXT     NULL,
                companyId    INT          NOT NULL
              )
                ENGINE = InnoDB;'
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run lint
  - npm run compile
  - npm run test